PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS schema_info(version INTEGER NOT NULL);
INSERT INTO schema_info SELECT 1 WHERE NOT EXISTS(SELECT 1 FROM schema_info);
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS cafes(id TEXT PRIMARY KEY,naver_id TEXT UNIQUE,code TEXT NOT NULL,name TEXT NOT NULL,url TEXT NOT NULL UNIQUE,active INTEGER NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS keywords(id TEXT PRIMARY KEY,name TEXT NOT NULL,normalized TEXT NOT NULL UNIQUE,active INTEGER NOT NULL,deleted INTEGER NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS posts(id INTEGER PRIMARY KEY,cafe_id TEXT NOT NULL REFERENCES cafes(id),article_id TEXT NOT NULL,first_collected_at TEXT NOT NULL,last_checked_at TEXT NOT NULL,latest_version_id INTEGER,UNIQUE(cafe_id,article_id));
CREATE TABLE IF NOT EXISTS post_versions(id INTEGER PRIMARY KEY,post_id INTEGER NOT NULL REFERENCES posts(id),fingerprint TEXT NOT NULL,title TEXT NOT NULL,raw TEXT NOT NULL,published_at TEXT,url TEXT NOT NULL,source_json TEXT NOT NULL,observed_at TEXT NOT NULL,UNIQUE(post_id,fingerprint));
CREATE TABLE IF NOT EXISTS post_keywords(post_id INTEGER NOT NULL REFERENCES posts(id),keyword_id TEXT NOT NULL REFERENCES keywords(id),first_seen_at TEXT NOT NULL,last_seen_at TEXT NOT NULL,PRIMARY KEY(post_id,keyword_id));
CREATE TABLE IF NOT EXISTS runs(id TEXT PRIMARY KEY,request_id TEXT UNIQUE,trigger TEXT NOT NULL,state TEXT NOT NULL,stage TEXT NOT NULL,started_at TEXT NOT NULL,ended_at TEXT,updated_at TEXT NOT NULL,settings_json TEXT NOT NULL,source_run_id TEXT REFERENCES runs(id),record_json TEXT NOT NULL,stop_requested INTEGER NOT NULL DEFAULT 0);
CREATE UNIQUE INDEX IF NOT EXISTS one_active_run ON runs((1)) WHERE state IN ('queued','running','stopping');
CREATE TABLE IF NOT EXISTS run_cafes(run_id TEXT NOT NULL REFERENCES runs(id),cafe_id TEXT NOT NULL REFERENCES cafes(id),start_at TEXT NOT NULL,end_at TEXT NOT NULL,status TEXT NOT NULL,count INTEGER,error TEXT,PRIMARY KEY(run_id,cafe_id));
CREATE TABLE IF NOT EXISTS analyses(id INTEGER PRIMARY KEY,version_id INTEGER NOT NULL REFERENCES post_versions(id),run_id TEXT NOT NULL REFERENCES runs(id),result_json TEXT NOT NULL,created_at TEXT NOT NULL,phase TEXT NOT NULL,UNIQUE(run_id,version_id,phase));
CREATE TABLE IF NOT EXISTS run_posts(run_id TEXT NOT NULL REFERENCES runs(id),post_id INTEGER NOT NULL REFERENCES posts(id),version_id INTEGER NOT NULL REFERENCES post_versions(id),analysis_id INTEGER REFERENCES analyses(id),included INTEGER NOT NULL,disposition TEXT NOT NULL,matched_json TEXT NOT NULL,engine_json TEXT NOT NULL,PRIMARY KEY(run_id,post_id));
CREATE TABLE IF NOT EXISTS reviews(id INTEGER PRIMARY KEY,analysis_id INTEGER NOT NULL REFERENCES analyses(id),state TEXT NOT NULL,note TEXT NOT NULL,reviewed_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS artifacts(id TEXT PRIMARY KEY,run_id TEXT NOT NULL REFERENCES runs(id),kind TEXT NOT NULL,path TEXT NOT NULL,sha256 TEXT NOT NULL,size INTEGER NOT NULL,created_at TEXT NOT NULL,UNIQUE(run_id,kind,path));
CREATE TABLE IF NOT EXISTS mail_logs(id INTEGER PRIMARY KEY,run_id TEXT NOT NULL UNIQUE REFERENCES runs(id),state TEXT NOT NULL,recipients_json TEXT NOT NULL,attachment_id TEXT REFERENCES artifacts(id),started_at TEXT,finished_at TEXT,result_json TEXT);
CREATE TABLE IF NOT EXISTS cursors(cafe_id TEXT PRIMARY KEY REFERENCES cafes(id),completed_until TEXT NOT NULL,run_id TEXT NOT NULL REFERENCES runs(id));
CREATE TABLE IF NOT EXISTS logs(id INTEGER PRIMARY KEY,run_id TEXT NOT NULL REFERENCES runs(id),at TEXT NOT NULL,level TEXT NOT NULL,message TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS imports(source TEXT PRIMARY KEY,sha256 TEXT NOT NULL,run_id TEXT NOT NULL REFERENCES runs(id),imported_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS runs_started ON runs(started_at DESC);
CREATE INDEX IF NOT EXISTS versions_post ON post_versions(post_id,observed_at);
CREATE INDEX IF NOT EXISTS run_posts_version ON run_posts(version_id);
CREATE INDEX IF NOT EXISTS analyses_version ON analyses(version_id,id DESC);
CREATE INDEX IF NOT EXISTS reviews_analysis ON reviews(analysis_id,id DESC);
CREATE INDEX IF NOT EXISTS logs_run ON logs(run_id,id);
