"""Inspect old Windows tasks; disable only one explicitly selected, owned task.

Default is read-only. No task is deleted, started or automatically registered.
Collection history and cursors are never modified by this module.
"""
import argparse
from datetime import datetime
import json
import ntpath
import os
from pathlib import Path
import re
import subprocess
import tempfile
import uuid

from v8.configuration import KST, read_json, write_json


def windows_path(value):
    value = str(value or '').strip().strip('"')
    if not ntpath.isabs(value) or '%' in value:
        return None
    return ntpath.normcase(ntpath.normpath(value))


def classify_task(task, project_root, task_name, *, legacy_roots=()):
    """A matching name is a hint, never sufficient authority to disable a task."""
    result = {'kind': 'review', 'can_disable': False, 'reason': '실행 명령을 수동으로 확인하세요.'}
    actions = task.get('actions') or []
    if len(actions) != 1:
        return result
    action = actions[0]
    working = windows_path(action.get('working_directory'))
    python = windows_path(action.get('execute'))
    if not working or not python:
        return result
    current = windows_path(project_root)
    allowed = {current} | {windows_path(p) for p in legacy_roots}
    if working not in allowed:
        return dict(result, kind='other_location', reason='다른 폴더의 작업입니다. 확인한 이전 폴더만 --legacy-root로 지정하세요.')
    arguments = action.get('arguments') or ''
    version = None
    if python == ntpath.join(working, '.venv', 'scripts', 'python.exe'):
        # Reconstruct exactly the command generated by V5; no shell parsing.
        v5 = [ntpath.join(working, 'v5', 'main_v5.py'), 'sync', '--scheduled', '--config',
              ntpath.join(working, 'config_v5.json')]
        name = task.get('name', '')
        if (re.fullmatch(r'NaverCafe_V5_[a-f0-9]{12}', name)
                and task.get('description') == 'NaverCafe V5 owned task ' + name
                and arguments.replace('/', '\\').casefold() == subprocess.list2cmdline(v5).casefold()):
            version = 'v5'
    elif python == ntpath.join(working, '.venv_v6', 'scripts', 'python.exe'):
        for candidate in ('v8', 'v9'):
            expected = '-u "' + ntpath.join(working, candidate, 'main.py') + '" run'
            if arguments.replace('/', '\\').casefold() == expected.casefold():
                version = candidate
                break
        if version and task.get('name') != task_name and not re.fullmatch(r'NaverCafe_[A-Za-z0-9_-]+', task.get('name', '')):
            return result
        # Explicit roots + exact executable/args are required in addition to name.
    if version is None:
        return result
    if version == 'v9' and working == current:
        return dict(result, kind='current_v9', reason='현재 프로젝트의 V9 실행 작업은 유지합니다.')
    if task.get('state') == 'Running':
        return dict(result, kind='running', reason='실행 중입니다. 종료한 뒤 다시 조회하세요.')
    if task.get('state') == 'Disabled':
        return dict(result, kind='already_disabled', reason='이미 비활성화되어 있습니다.')
    return dict(kind='legacy', can_disable=True, reason=f'확인된 {version.upper()} 작업: 개별 비활성화 가능')


def powershell(action, request=None):
    if os.name != 'nt':
        raise RuntimeError('이 기능은 예약 작업이 등록된 Windows PC에서 실행하세요.')
    script = Path(__file__).with_name('schedule_tasks.ps1')
    command = ['powershell.exe', '-NoProfile', '-NonInteractive', '-File', str(script), '-Action', action]
    with tempfile.TemporaryDirectory(prefix='naver_schedule_') as temp:
        if request is not None:
            path = Path(temp) / 'request.json'
            write_json(path, request)
            command += ['-RequestFile', str(path)]
        # Do not override corporate PowerShell execution policy.
        completed = subprocess.run(command, capture_output=True, encoding='utf-8-sig', errors='replace', timeout=90)
        if completed.returncode:
            raise RuntimeError((completed.stderr or completed.stdout).strip())
        return json.loads(completed.stdout)


def inventory(project, legacy_roots=()):
    configured_name = read_json(project / 'config_v9.json')['schedule']['task_name']
    tasks = powershell('list')
    tasks = tasks if isinstance(tasks, list) else [tasks] if tasks else []
    rows = []
    for task in tasks:
        row = dict(task, classification=classify_task(task, str(project), configured_name,
                                                   legacy_roots=legacy_roots))
        rows.append(row)
    rows.sort(key=lambda r: (r.get('path', ''), r.get('name', '')))
    return {'created_at': datetime.now(KST).isoformat(), 'project_root': str(project),
            'configured_task_name': configured_name, 'tasks': rows}


def disable_selected(project, snapshot, index, *, legacy_roots=()):
    if windows_path(snapshot.get('project_root')) != windows_path(project):
        raise ValueError('조회한 프로젝트 폴더와 현재 폴더가 다릅니다.')
    if index < 1 or index > len(snapshot['tasks']):
        raise ValueError('조회 결과의 작업 번호를 선택하세요.')
    task = snapshot['tasks'][index - 1]
    # Ignore saved classification; re-evaluate ownership with current settings.
    name = read_json(project / 'config_v9.json')['schedule']['task_name']
    check = classify_task(task, str(project), name, legacy_roots=legacy_roots)
    if not check['can_disable']:
        raise ValueError(check['reason'])
    backup = project / 'output_v9' / 'schedule_backups' / (
        'legacy_' + datetime.now(KST).strftime('%Y%m%d_%H%M%S_%f') + '_' + uuid.uuid4().hex[:6] + '.xml')
    return powershell('disable', {'name': task['name'], 'path': task['path'],
                                 'expected_xml': task['xml'], 'backup_path': str(backup)})


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--project-root', type=Path, default=Path(__file__).resolve().parent.parent)
    parser.add_argument('--legacy-root', action='append', default=[], help='확인한 이전 프로젝트 폴더, 여러 번 지정 가능')
    parser.add_argument('--snapshot', type=Path, help='51번 조회에서 저장한 schedule_inventory.json')
    parser.add_argument('--disable-index', type=int, help='조회 결과의 한 작업만 XML 백업 후 비활성화')
    args = parser.parse_args(argv)
    project = args.project_root.resolve()
    try:
        if args.disable_index is not None:
            if args.snapshot is None:
                raise ValueError('--snapshot과 --disable-index를 함께 지정하세요.')
            result = disable_selected(project, read_json(args.snapshot), args.disable_index,
                                      legacy_roots=args.legacy_root)
            print('[예약 비활성화]', result['name'])
            print('[복구용 XML]', result['backup_path'])
            print('예약 등록은 유지됩니다. 다시 사용하려면 작업 스케줄러에서 해당 작업을 사용으로 전환하세요.')
            return 0
        snapshot = inventory(project, args.legacy_root)
        folder = project / 'output_v9' / 'schedule_inspection' / datetime.now(KST).strftime('%Y%m%d_%H%M%S_%f')
        folder.mkdir(parents=True, exist_ok=False)
        path = folder / 'schedule_inventory.json'
        write_json(path, snapshot)
        print('[예약 조회] 변경 없음 / 현재 V9 및 다른 프로그램 작업 유지')
        for i, task in enumerate(snapshot['tasks'], 1):
            print(f"{i}. {task['path']}{task['name']} / {task['state']} / {task['classification']['reason']}")
            for action in task['actions']:
                print('   실행:', action['execute'], action['arguments'])
                print('   폴더:', action['working_directory'])
            print('   트리거:', json.dumps(task['triggers'], ensure_ascii=False))
            print('   놓친 예약 나중 실행:', task.get('start_when_available'), '/ 다음 실행:', task.get('next_run'))
        print('[조회 저장]', path)
        print('비활성화하려면 같은 프로젝트에서 다음 명령에 작업 번호를 넣으세요:')
        command = ['.venv_v6\\Scripts\\python.exe', '-m', 'v9.schedule_tasks', '--snapshot', str(path)]
        for legacy_root in args.legacy_root:
            command += ['--legacy-root', legacy_root]
        print(subprocess.list2cmdline(command) + ' --disable-index 번호')
        return 0
    except (ValueError, OSError, RuntimeError, subprocess.TimeoutExpired) as exc:
        print('[예약 확인 실패]', str(exc))
        print('실행 정책 또는 권한 오류라면 Windows 작업 스케줄러에서 같은 작업을 직접 확인하세요.')
        return 1


if __name__ == '__main__':
    raise SystemExit(main())
